[package]
name = "tomatl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17"
colored = "2.0"
figlet-rs = "0.1"
notify-rust = "4.8"
rodio = "0.17"
rusqlite = { version = "0.29", features = ["bundled"] }
chrono = "0.4"
